### ISSUE TITLE
TypeError: client_secret_basic client authentication method requires a client_secret

### ISSUE THREAD

**Issue by robbertkl** [idiidk/magister-openid#2]
After applying https://github.com/simplyGits/MagisterJS/pull/150 and #1, I'm still getting this error from within `getTokenSet()`:

```
TypeError: client_secret_basic client authentication method requires a client_secret
```

Please note I'm not getting this error when using the latest magister.js release (2.0.0-alpha.12, which does not yet use magister-openid) with a manually applied change to the new challenge URLs.

**Comment by idiidk** [comment]
Pretty strange that this broke. Just added token_endpoint_auth_method: "none" to the client initialization which fixes it. Don't know why it worked in the first place tho. Sometimes code is just weird I guess :D

Thanks for the pull request btw!

**Comment by robbertkl** [comment]
Awesome, thanks for the fix. Will there be a new version release?

**Comment by idiidk** [comment]
Pushed 0.1.5 to npm :)
